version: '3'

services:
  node:
    build: .
    container_name: blogs_api_node
    restart: always
    workingDir: /app
    volumes: 
      - ./:/app
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: blogs-api
      HOSTNAME: db
  db:
    container_name: blogs_api_db
    image: mysql:8.0.21
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

volumes:
  db:

networks:
  default:
    name: blogs_api_network
