version: '3'

services:
  node:
    build: .
    container_name: blogs_api_node
    restart: always
    working_dir: /app
    volumes: 
      - ./:/app
    tty: true
    stdin_open: true
    command: bash
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: blogs-api
      HOSTNAME: db
  db:
    container_name: blogs_api_database
    image: mysql:8.0.21
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

networks:
  default:
    name: blogs_api_network
